<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="WKWIN5154091" failures="1" tests="5" name="Test" time="0.11" errors="0" timestamp="2019-11-22T12:54:27 IST">
  <testcase classname="learnTestNG.RetryConcept" name="test1" time="0.015">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="learnTestNG.RetryConcept" name="test1" time="0.002">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="learnTestNG.RetryConcept" name="test1" time="0.002">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="learnTestNG.RetryConcept" name="test1" time="0.003">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at learnTestNG.RetryConcept.test1(RetryConcept.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="learnTestNG.RetryConcept" name="test2" time="0.006"/>
</testsuite> <!-- Test -->
